services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    container_name: financial-api-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: financial-api-frontend
    restart: unless-stopped
    environment:
      - API_URL=http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
